# Generated by Django 2.2.3 on 2019-07-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('en_name', models.CharField(max_length=128, unique=True)),
                ('joined_at', models.DateField()),
                ('quited_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('en_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('en_author', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('en_title', models.CharField(max_length=128)),
                ('vol', models.CharField(blank=True, max_length=32, null=True)),
                ('no', models.CharField(blank=True, max_length=32, null=True)),
                ('page', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('main_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gyoseki.Author')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gyoseki.Conf')),
            ],
        ),
    ]
