# Generated by Django 2.2.3 on 2019-11-03 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyoseki', '0002_auto_20190905_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='recode',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recode',
            name='tag',
            field=models.ManyToManyField(blank=True, to='gyoseki.Tag'),
        ),
        migrations.AddField(
            model_name='recode',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gyoseki.Language'),
        ),
    ]
