# Generated by Django 2.2.3 on 2019-11-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gyoseki', '0003_auto_20191103_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recode',
            name='en_author',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recode',
            name='en_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recode',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recode',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
