# Generated by Django 2.2.3 on 2019-11-25 04:31

from django.db import migrations, models
import gyoseki.models


class Migration(migrations.Migration):

    dependencies = [
        ('gyoseki', '0004_auto_20191120_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recode',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=gyoseki.models.get_upload_to),
        ),
    ]
