# Generated by Django 2.2.3 on 2019-12-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyoseki', '0005_auto_20191125_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='en_name',
            field=models.CharField(max_length=128),
        ),
    ]
