# Generated by Django 2.2.3 on 2019-12-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyoseki', '0006_auto_20191205_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recode',
            name='author',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='recode',
            name='no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recode',
            name='page',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recode',
            name='vol',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
